### PR TITLE
Revert "Remove unneeded files update gitignore"

### PR DESCRIPTION
**Pull request by avjinder**
Reverts avjinder/Minimal-Todo#3

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
Was there something wrong with the gitignore? I use it in all my project and have never had an issue with it.

**Comment by avjinder** [comment]
The .gitignore is perfect, I've even saved it so I can use it in all my other projects. I'm new to Github, so when I merged your pull request, and then pulled down to my system, Android Studio removed all my .idea files, rendering the project unable to be loaded and used. 

So, I had to go back to a previous commit and start from there. This is embarrassing for me, I'm not used to git yet, still getting the hang of it.

**Comment by Jawnnypoo** [comment]
No worries, since .idea files are very Android Studio specific, it was probably expecting to see specific ones and when they were removed, it got confused. Usually when you do a major removal of files like that, you would likely have to redownload the repo and do the whole "File->Open existing Android Studio Project" then navigate to the topmost `build.gradle` and it would do the rest.

**Comment by avjinder** [comment]
Oh, I'll merge your pull request and try to do that. Thanks.

**Comment by karansinghkjs346** [comment]
Hello Everyone , 
i am new to android and want to contribute to Android projects to fill the covers of my knowledge , can you please help me our a lil bit so that i can start ?

**Pull request merged**
