### PR TITLE
Added language support for Finnish & implemented some test cases

### PR DESCRIPTION
**Pull request by miikande**
Added support for Finnish language. Implemented also some test cases for ToDoItem and StoreRetrieveData classes.

### CODE REVIEW

**Comment by miikande** [comment]
Any comments on this change?

**Comment by piotrek1543** [comment]
@miikande change README.md file - add yourself as translator :+1: 
@avjinder, please merge this pull request

**Comment by miikande** [comment]
@piotrek1543 README.md should already be OK, you can check the file content by viewing "Files changed"

**Comment by piotrek1543** [comment]
@miikande  Now I have no question. Good pull request

**Comment by miikande** [comment]
@piotrek1543 cheers mate!

**Pull request merged**
